web:
  image: keviocastro/elgg-docker:2.3
  ports:
    - "8080:80"
  links:
    - mysql
  volumes:
    - .:/var/www/html/
    - ~/.composer:/root/.composer/
  environment:
    # db
    ELGG_DB_USER: root
    ELGG_DB_PASS: secret
    ELGG_DB_NAME: redeitego
    ELGG_DB_HOST: mysql
    # Admin user
    ELGG_USERNAME: admin
    ELGG_PASSWORD: secret
    # Deployment Settings
    ELGG_WWW_ROOT: http://localhost:8080
    ELGG_PATH: /var/www/html/
    ELGG_DATA_ROOT: /media/elgg/
    # Site settings
    ELGG_SITE_ACCESS: 2
    # Access tokens to external services 
    #GITHUB_PERSONAL_ACESS_TOKEN: 
mysql:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: redeitego
    MYSQL_ROOT_PASSWORD: secret